# .github/workflows/app.yaml
name: Project Tests
on: push
#testing workflows
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install package
        run: |
          pip install . 
      - name: Test with pytest
        run: |
          python -m pytest -vv tests/*py